/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'savinderchauhan' at '8/18/16 1:19 AM' with Gradle 2.13
 *
 * @author savinderchauhan, @date 8/18/16 1:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
